### ISSUE TITLE
popup html file location bug

### ISSUE THREAD

**Issue by Benbinbin** [yeqisong/crx3-dev-template#3]
after build or watch, the popup and newTab page can't show img correctly, it seems **the wrong path of `js` files in these HTML files** cause this problem. 

After build or watch, the `popup.html` or `newtab.html` files will be placed in `libs` folder, but inside these HTML the `js` file link is `/assets/vendor.cd8ea3c0.js`, they're wrong.

![Snipaste_2021-09-06_14-14-57](https://user-images.githubusercontent.com/40909550/132169563-85fcd736-c16d-4b82-b20c-25360218d918.png)

one solution is put the `popup.html` or `newtab.html` files in the `src` folder, so that after build or watch, it can refer to the correct path of the javascript files in `assets` folder.

**Comment by yeqisong** [comment]
can you show me the code in manifest.json which in src dir.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yeqisong/crx3-dev-template"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月6日(星期一) 下午2:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[yeqisong/crx3-dev-template] popup html file location bug (#3)





 
after build or watch, the popup and newTab page can't show img correctly, it seems the wrong path of js files in these HTML files cause this problem.
 
After build or watch, the popup.html or newtab.html files will be placed in libs folder, but inside these HTML the js file link is /assets/vendor.cd8ea3c0.js, they're wrong.
 

 
one solution is put the popup.html or newtab.html files in the src folder, so that after build or watch, it can refer to the correct path of the javascript files in assets folder.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Benbinbin** [comment]
I clone this template and **only modify the `{{appxxx}}`** (like `{{appTitle}}`) section in `package.json` file and `messages.json` in `_locales` folder,  other part is the same as this template

**Comment by yeqisong** [comment]
> after build or watch, the popup and newTab page can't show img correctly, it seems **the wrong path of `js` files in these HTML files** cause this problem.
> 
> After build or watch, the `popup.html` or `newtab.html` files will be placed in `libs` folder, but inside these HTML the `js` file link is `/assets/vendor.cd8ea3c0.js`, they're wrong.
> 
> ![Snipaste_2021-09-06_14-14-57](https://user-images.githubusercontent.com/40909550/132169563-85fcd736-c16d-4b82-b20c-25360218d918.png)
> 
> one solution is put the `popup.html` or `newtab.html` files in the `src` folder, so that after build or watch, it can refer to the correct path of the javascript files in `assets` folder.

已经修复！将crx3升级到1.0.7即可。原因：部分资源编译时，在windows下”/“处理不当导致的。
